##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.4.0-B60] date: [Tue Aug 20 20:15:41 CST 2024] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = Basic_Framework_MC02


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/memory_regions.c \
Core/Src/gpio.c \
Core/Src/freertos.c \
Core/Src/adc.c \
Core/Src/dma.c \
Core/Src/fdcan.c \
Core/Src/octospi.c \
Core/Src/spi.c \
Core/Src/tim.c \
Core/Src/usart.c \
Core/Src/stm32h7xx_it.c \
Core/Src/stm32h7xx_hal_msp.c \
Core/Src/stm32h7xx_hal_timebase_tim.c \
USB_DEVICE/App/usb_device.c \
USB_DEVICE/App/usbd_desc.c \
USB_DEVICE/App/usbd_cdc_if.c \
USB_DEVICE/Target/usbd_conf.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pcd.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pcd_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_usb.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_gpio.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hsem.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mdma.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cortex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_exti.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_adc.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_adc_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_fdcan.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_ospi.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_spi.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_spi_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart_ex.c \
Core/Src/system_stm32h7xx.c \
Middlewares/Third_Party/FreeRTOS/Source/croutine.c \
Middlewares/Third_Party/FreeRTOS/Source/event_groups.c \
Middlewares/Third_Party/FreeRTOS/Source/list.c \
Middlewares/Third_Party/FreeRTOS/Source/queue.c \
Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c \
Middlewares/Third_Party/FreeRTOS/Source/tasks.c \
Middlewares/Third_Party/FreeRTOS/Source/timers.c \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.c \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c \
Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c \
Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c \
Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c \
Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c \
Middlewares/Third_Party/SEGGER/RTT/SEGGER_RTT_printf.c \
Middlewares/Third_Party/SEGGER/RTT/SEGGER_RTT.c \
Core/Src/sysmem.c \
Core/Src/syscalls.c \
bsp/dwt/bsp_dwt.c \
bsp/pwm/bsp_pwm.c \
bsp/gpio/bsp_gpio.c \
bsp/spi/bsp_spi.c \
bsp/iic/bsp_iic.c \
bsp/can/bsp_can.c \
bsp/usart/bsp_usart.c \
bsp/log/bsp_log.c \
bsp/bsp_tools.c \
modules/algorithm/controller.c \
modules/algorithm/kalman_filter.c \
modules/algorithm/QuaternionEKF.c \
modules/algorithm/crc8.c \
modules/algorithm/crc16.c \
modules/algorithm/user_lib.c \
modules/algorithm/lqr.c \
modules/algorithm/leso.c \
modules/algorithm/adrc.c \
modules/bluetooth/HC05.c \
modules/BMI088/bmi088.c \
modules/imu/BMI088driver.c \
modules/imu/BMI088Middleware.c \
modules/imu/ins_task.c \
modules/master_machine/master_process.c \
modules/master_machine/seasky_protocol.c \
modules/motor/DJImotor/dji_motor.c \
modules/motor/HTmotor/HT04.c \
modules/motor/LKmotor/LK9025.c \
modules/motor/DMmotor/dmmotor.c \
modules/motor/step_motor/step_motor.c \
modules/motor/servo_motor/servo_motor.c \
modules/motor/motor_task.c \
modules/oled/oled.c \
modules/referee/crc_ref.c \
modules/referee/rm_referee.c \
modules/referee/referee_UI.c \
modules/referee/referee_task.c \
modules/remote/remote_control.c \
modules/remote/flysky.c \
modules/super_cap/super_cap.c \
modules/can_comm/can_comm.c \
modules/message_center/message_center.c \
modules/daemon/daemon.c \
modules/alarm/buzzer.c \
modules/vofa/vofa.c \
application/gimbal/gimbal.c \
application/chassis/balance.c \
application/chassis/balance_nmpc.c \
application/chassis/balance_state.c \
application/chassis/balance_control.c \
application/shoot/shoot.c \
application/cmd/robot_cmd.c \
application/buzzer/buzzer_app.c \
application/robot.c \
Core/Src/i2c.c

# ASM sources
ASM_SOURCES =  \
startup_stm32h723xx.s \
Middlewares/Third_Party/SEGGER/RTT/SEGGER_RTT_ASM_ARMv7M.s

# ASM sources
ASMM_SOURCES = 


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m7

# fpu
FPU = -mfpu=fpv5-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32H723xx \
-DARM_MATH_CM7 \
-DDISABLE_LOG_SYSTEM 


# AS includes
AS_INCLUDES =  \
-ICore/Inc

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IUSB_DEVICE/App \
-IUSB_DEVICE/Target \
-IDrivers/STM32H7xx_HAL_Driver/Inc \
-IDrivers/STM32H7xx_HAL_Driver/Inc/Legacy \
-IMiddlewares/Third_Party/FreeRTOS/Source/include \
-IMiddlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS \
-IMiddlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F \
-IMiddlewares/ST/STM32_USB_Device_Library/Core/Inc \
-IMiddlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc \
-IDrivers/CMSIS/Device/ST/STM32H7xx/Include \
-IDrivers/CMSIS/Include \
-Iapplication/chassis \
-Iapplication/shoot \
-Iapplication/gimbal \
-Iapplication/cmd \
-Iapplication/tcm_region \
-Iapplication \
-Ibsp/dwt \
-Ibsp/can \
-Ibsp/usart \
-Ibsp/gpio \
-Ibsp/spi \
-Ibsp/iic \
-Ibsp/log \
-Ibsp/pwm \
-Ibsp \
-Imodules/algorithm \
-Imodules/bluetooth \
-Imodules/BMI088 \
-Imodules/imu \
-Imodules/master_machine \
-Imodules/motor/DJImotor \
-Imodules/motor/LKmotor \
-Imodules/motor/HTmotor \
-Imodules/motor/step_motor \
-Imodules/motor/servo_motor \
-Imodules/motor/DMmotor \
-Imodules/motor \
-Imodules/oled \
-Imodules/referee \
-Imodules/remote \
-Imodules/super_cap \
-Imodules/can_comm \
-Imodules/message_center \
-Imodules/daemon \
-Imodules/alarm \
-Imodules/vofa \
-Imodules \
-IMiddlewares/ST/ARM/DSP/Inc \
-IMiddlewares/ST/ARM/DSP/Include/dsp \
-IMiddlewares/Third_Party/SEGGER/RTT \
-IMiddlewares/Third_Party/SEGGER/Config



# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32H723VGTx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys -larm_cortexM7lfdp_math
LIBDIR = -LDrivers/CMSIS/DSP/Lib/GCC
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections,--print-memory-usage

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin



#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@
$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	rd $(BUILD_DIR) /s/q

#######################################
# TCM placement verification
# Usage: make tcm-check ITCM_SYMS="Func1 Func2" DTCM_SYMS="g_var1 g_var2"
# Or just: make tcm-check  (uses default symbol list below)
#######################################
NM = $(PREFIX)nm

# Default symbols to verify — update these to match your actual function/variable names
ITCM_CHECK_SYMS ?= \
	WBC_JacobianUpdate \
	WBC_TorqueAllocation \
	FiveLink_ForwardKinematics \
	FiveLink_InverseKinematics \
	MPC_PredictStep \
	QuaternionUpdate

DTCM_CHECK_SYMS ?= \
	g_J_wbc \
	g_tau_wbc \
	g_q_five_link \
	g_mpc_x \
	kFiveLinkLen \
	kMpcWeightQ

# ITCM  address range: 0x00000000 - 0x0000FFFF (64KB)
# DTCM  address range: 0x20000000 - 0x2001FFFF (128KB)
# FLASH address range: 0x08000000 - 0x080FFFFF (1024KB)
# AXI SRAM            0x24000000 - 0x2401FFFF (128KB)

tcm-check: $(BUILD_DIR)/$(TARGET).elf
	@echo ""
	@echo "=========================================================="
	@echo "  TCM Placement Verification"
	@echo "=========================================================="
	@echo ""
	@echo "--- ITCM functions (expect addr: 0x000xxxxx) ---"
	@for sym in $(ITCM_CHECK_SYMS); do \
		result=$$($(NM) $< 2>/dev/null | grep -w "$$sym"); \
		if [ -z "$$result" ]; then \
			echo "  [NOT FOUND] $$sym  <- not compiled or name mismatch"; \
		else \
			addr=$$(echo $$result | awk '{print $$1}'); \
			section=$$(echo $$result | awk '{print $$2}'); \
			prefix=$$(echo $$addr | cut -c1-4); \
			if [ "$$prefix" = "0000" ]; then \
				echo "  [ITCM  OK ] $$sym  @ 0x$$addr"; \
			elif [ "$$prefix" = "0800" ] || [ "$$prefix" = "0801" ]; then \
				echo "  [!! FLASH ] $$sym  @ 0x$$addr  <- ITCM_FUNC not applied!"; \
			else \
				echo "  [?? OTHER ] $$sym  @ 0x$$addr  ($$section)"; \
			fi; \
		fi; \
	done
	@echo ""
	@echo "--- DTCM data   (expect addr: 0x200xxxxx) ---"
	@for sym in $(DTCM_CHECK_SYMS); do \
		result=$$($(NM) $< 2>/dev/null | grep -w "$$sym"); \
		if [ -z "$$result" ]; then \
			echo "  [NOT FOUND] $$sym  <- not compiled or name mismatch"; \
		else \
			addr=$$(echo $$result | awk '{print $$1}'); \
			section=$$(echo $$result | awk '{print $$2}'); \
			prefix=$$(echo $$addr | cut -c1-4); \
			if [ "$$prefix" = "2000" ]; then \
				echo "  [DTCM  OK ] $$sym  @ 0x$$addr"; \
			elif [ "$$prefix" = "2400" ] || [ "$$prefix" = "2401" ]; then \
				echo "  [!! AXI   ] $$sym  @ 0x$$addr  <- DTCM_BSS/DATA not applied!"; \
			else \
				echo "  [?? OTHER ] $$sym  @ 0x$$addr  ($$section)"; \
			fi; \
		fi; \
	done
	@echo ""
	@echo "--- Memory region usage summary ---"
	@$(NM) --print-size --size-sort --radix=d $< 2>/dev/null | awk '\
		BEGIN { itcm=0; dtcm=0; axi=0; flash_code=0 } \
		{ \
			addr=strtonum("0x"$$1); size=strtonum("0x"$$2); \
			if (addr >= 0 && addr < 65536)          { itcm  += size } \
			else if (addr >= 536870912 && addr < 536936448) { dtcm  += size } \
			else if (addr >= 603979776 && addr < 604044312) { axi   += size } \
			else if (addr >= 134217728 && addr < 135266304) { flash_code += size } \
		} \
		END { \
			printf "  ITCM  used: %6d B / 65536  B  (%.1f%%)\n", itcm,  itcm/65536*100; \
			printf "  DTCM  used: %6d B / 131072 B  (%.1f%%)\n", dtcm,  dtcm/131072*100; \
			printf "  AXI   used: %6d B / 131072 B  (%.1f%%)\n", axi,   axi/131072*100; \
			printf "  FLASH used: %6d B / 1048576 B (%.1f%%)\n", flash_code, flash_code/1048576*100; \
		}'
	@echo "=========================================================="
	@echo ""

#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
